version: '3.3'
services :
  db:
    image: postgres
    ports:
      - "6000:6000"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: WPFP
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - "8070:8070"